### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Xyndra** [hparcells/elemental-reborn#21]
Its down sadge

**Comment by hparcells** [comment]
It doesn't seem to be down now, at least for me. Can you provide more details? Does the game not load? Are you getting a "Service Unavailable" page?

It should also be noted that the domain of Elemental Reborn has changed **multiple times**, and depending on where you had learned Elemental Reborn existed, you might have received the wrong URL. The current, and permanent, domain is at https://elemental.hunterparcells.com/.

**Comment by Xyndra** [comment]
Nevermind my PC buggin
